version: '3.3'
services:
  elasticsearch:
    build: docker/elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 4G
    
  kibana:
    build: docker/kibana
    container_name: kibana
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    volumes:
      - kibana_data:/usr/share/kibana/data
      - certs:/usr/share/kibana/config/certs
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

volumes:
  certs:
    driver: local
  es_data:
    driver: local
  kibana_data:
    driver: local

networks:
  elastic:
    driver: bridge
