name: CI

on:
  workflow_dispatch:
  push:
    branches: ['main', 'feat/dockerfiles']

jobs:
  elk-check-files-changed:
    runs-on: ubuntu-latest

    outputs:
      files-changed-elasticsearch: ${{ steps.set-output.outputs.files-changed-elasticsearch }}
      files-changed-kibana: ${{ steps.set-output.outputs.files-changed-kibana }}

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files in docker for elasticsearch
        id: check-files-elasticsearch
        uses: tj-actions/changed-files@v37
        with:
          files: docker/elasticsearch
      
      - name: Get changed files in docker for kibana
        id: check-files-kibana
        uses: tj-actions/changed-files@v37
        with:
          files: docker/kibana
      
      - name: Set output if files changed in docker for elasticsearch and kibana
        id: set-output
        run: |
          echo "files-changed-elasticsearch=${{ steps.check-files-elasticsearch.outputs.any_changed }}" >> $GITHUB_OUTPUT
          echo "files-changed-kibana=${{ steps.check-files-kibana.outputs.any_changed }}" >> $GITHUB_OUTPUT

  elasticsearch-build:
    needs: elk-check-files-changed
    if: ${{ needs.elk-check-files-changed.outputs.files-changed-elasticsearch == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  kibana-build:
    needs: elk-check-files-changed
    if: ${{ needs.elk-check-files-changed.outputs.files-changed-kibana == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  webapp-build:
    runs-on: ubuntu-latest
    env:
      working-directory: webapp-next

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn --frozen-lockfile

      - name: Build webapp
        working-directory: ${{ env.working-directory }}
        run: yarn build
